apiVersion: packages.glasskube.dev/v1alpha1
kind: ClusterPackage
metadata:
  name: cert-manager
spec:
  packageInfo:
    name: cert-manager
    repositoryName: glasskube
    version: v1.13.3+1
status: {}

