apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: glasskube-packages
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/christophenne/glasskube-argocd-demo
        revision: HEAD
        directories:
          - path: 'packages'
  template:
    metadata:
      name: '{{ .path.basename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/christophenne/glasskube-argocd-demo
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
