apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/kube-prometheus-stack/clusterpackage.yaml
    repoURL: https://github.com/christophenne/glasskube-argocd-demo
    targetRevision: HEAD
